// Renglones abreviados de prueba (inventados) y el producto correcto del catálogo, o null si no está.
// «ajuste» se usó para calibrar las reglas; «control» se escribió después y no se usó para ajustar.
module.exports.ajuste=[
  ['GAS.MANAOS COLA 2,25LTX6','Manaos Cola 2,25 L','Limón Autoservicio Mayorista'],
  ['GASEOSA MANAOS LIMA 2.25L X6','Manaos Lima 2,25 L',''],
  ['CERV.ISENBECK LAT 473CC X24','Lata Cerveza Isenbeck 473ml',''],
  ['CERV ISENBECK LATA 473','Lata Cerveza Isenbeck 473ml',''],
  ['FERNET BRANCA 750CC','Fernet Branca 750ml',''],
  ['FERNET BRANCA 1LT','Fernet Branca 1L',''],
  ['FERN.BRANCA 450','Fernet Branca 450ml',''],
  ['VDKA SKYY RASPB 750','Vodka Skyy Raspberry 750ml',''],
  ['VODKA SKYY COSMIC 750CC','Vodka Skyy Cosmic 750ml',''],
  ['SPEEDXLUNLIMITEDX473CCX6U-SP','Lata Speed 473ml',''],
  ['SPEED UNLIMITED LATA 250CC','Lata Speed 250ml',''],
  ['GALL.MEDIA TARDE CLAS.315G','Galletita Media Tarde Clasicas 315gr',''],
  ['GALL MEDIA TARDE SANDW 321G','Galletita Media Tarde Sandwich 321gr',''],
  ['CIG.MARLB.BOX 20','Cigarrillo Marlboro Box x20',''],
  ['MARLBORO COMUN X20','Cigarrillo Marlboro Comun x20',''],
  ['MARLBORO X10','Cigarrillo Marlboro x10',''],
  ['CHESTERFIELD COMUN X10','Cigarrillo Chesterfield Comun x10',''],
  ['PHILIP MORRIS BOX 20','Cigarrillo Philip Morris Box x20',''],
  ['AGUA V.MANAOS S/GAS 500X12','Agua Villamanaos 500 ml',''],
  ['AGUA VILLA MANAOS 2LT','Agua Villa Manaos 2 L',''],
  ['CC ZERO LAT 354X6','Lata Coca Cola Zero 354ml',''],
  ['COCA COLA 2.25 LT','Coca Cola 2,25L',''],
  ['COCA COLA ZERO 2,25','Coca Cola Zero 2,25L',''],
  ['ALF.GUAYMALLEN TRIP.CHOC','Alfajor Guaymallen Triple Chocolate 70gr',''],
  ['ALF GUAYMALLEN SIMPLE LCHE 38G','Alfajor Guaymallen Leche Simple 38gr',''],
  ['SMIRN.GREEN APPLE LT473','Lata Smirnoff Green Apple 473ml',''],
  ['PEPSI 2LT X6','Pepsi 2L',''],
  ['PEPSI LATA 354','Lata Pepsi 354ml',''],
  ['VINO STA JULIA 750','Vino Santa Julia 750ml',''],
  ['VINO VIÑAS DE BALBO TTO 1125','Vino Viñas de Balbo Tinto 1,125L',''],
  ['BAGGIO MULTIF.1LT','Baggio Multifruta 1L',''],
  ['BAGGIO MZNA 200ML','baggio manzana 200ml',''],
  ['YERBA PLAYADITO 500G','Yerba Playadito 500gr',''],
  ['YBA TARAGUI 500GR','Yerba Taragui 500gr',''],
  ['LATA FERNET 1882 473','Lata Fernet 1882 473ml',''],
  ['FERNET 1882 C/POMELO LATA 473','Lata Fernet con Pomelo 1882 473ml',''],
  ['7UP 2LT X 6','7UP 2L',''],
  ['SPRITE 2.25LT','Sprite 2,25L',''],
  ['PLACER POMELO 1.5LT','Placer Pomelo 1,5L',''],
  ['PLACER PERA 500CC','Placer Pera 500 ml',''],
  ['ACEITE GIRASOL LEIRA 900CC','Aceite de girasol Leira 900 cc',''],
  ['AZUCAR TANGO 900G','Azucar Tango 900gr',''],
  ['CERV.361 LAGER DESC.1LT','Cerveza 361 Lager Descartable 1L',''],
  ['PAPAS LAYS CLASICAS 77G','Papas Lays Clasicas 77gr',''],
  ['DORITOS QUESO 40GR','Snack Doritos Queso 40gr',''],
  ['MONSTER ULTRA LATA 473','Lata Monster Ultra 473ml',''],
  ['GATORADE MZNA 500','Gatorade Manzana 500 ml',''],
  ['FIDEOS LUCHETTI TIRABUZON 500G','Fideos Luchetti Tirabuzon 500gr',''],
  ['ARROZ MOLINOS ALA L.FINO 1KG','Arroz Largo Fino Molinos Ala 1kg',''],
  ['CHOC.COFLER BLOCK 110G','Chocolate Cofler Block 110gr',''],
  // No están en el catálogo: nunca deberían salir como «seguro».
  ['CERV.QUILMES CLASICA 1LT',null,''],
  ['GALL.OREO RELLENA 354G X3',null,''],
  ['VINO NORTON MALBEC 750',null,''],
  ['JUGO CEPITA DURAZNO 1.5LT',null,''],
  ['SALSA LISTA ARCOR 340G',null,''],
  ['MARLBORO GOLD BOX 20',null,''],
  ['CERV.QUILMES LATA 473',null,''],
  ['VODKA SMIRNOFF 700CC',null,''],
  ['ALF.FANTOCHE TRIPLE DULCE LECHE',null,''],
  ['GALL.MEDIA TARDE 3 PACK',null,''],
  ['COCA COLA 1.5LT',null,''],
  ['MANAOS COLA 3LT',null,''],
];
module.exports.control=[
  ['CERV.BRAHMA LATON 710','Laton Cerveza Brahma 710ml'],
  ['CERV BUDWEISER LAT 473X24','Lata Cerveza Budweiser 473ml'],
  ['CERV.CORONA BOT.330','Botella Cerveza Corona 330ml'],
  ['CERV CORONA 710CC','Botella Cerveza Corona 710ml'],
  ['STELLA ARTOIS 1LT RET','Stella Artois 1L'],
  ['GIN GORDONS PINK 700','Gin Gordons Premium Pink 700ml'],
  ['RON BACARDI 750CC','Ron Bacardi 750ml'],
  ['CHANDON DELICE 750','Chandon Delice 750ml'],
  ['APERITIVO CHANDON APERITIF 750','Chandon Aperitif 750ml'],
  ['MONSTER MANGO LOCO 473','Monster Mango Loco Celeste 473 ml'],
  ['AQUARIUS PERA 2.25LT','Aquarius Pera 2,25L'],
  ['AQUARIUS POMELO 600CC','Aquarius Pomelo 600ml'],
  ['CEPITA NARANJA 995','Cepita Naranja 995ml'],
  ['LECHE LA SERENISIMA 1LT','Leche Laserenisima 1L'],
  ['DDL LA SERENISIMA CLASICO 400G','Dulce de Leche La Serenisima Clasico 400gr'],
  ['YBA ROSAMONTE 500','Yerba Rosamonte 500gr'],
  ['YERBA UNION ORIG 500GR','Yerba Unión Original 500gr'],
  ['FIDEOS MAROLIO MOSTACHOL 500','Fideos Marolio Mostachol 500gr'],
  ['FID.MATARAZZO TALLARIN N11 500G','Fideos Matarazzo Tallarin N11 500gr'],
  ['HARINA PUREZA LEUD.1KG','Harina Pureza Leudante Ultra Refinada 1kg'],
  ['PURE TOMATE MAROLIO 520','Pure de Tomate Marolio 520gr'],
  ['MAYONESA NATURA 237G','Mayonesa Natura 237g'],
  ['ATUN S&P NATURAL DESMEN.120','Atun Desmenuzado S&P al Natural 120gr'],
  ['PAPAS PRINGLES ORIG 109','Papas Pringles Original Clasico 109gr'],
  ['CHEETOS QUESO 43G','Snack Cheetos Original Queso 43gr'],
  ['ALF.JORGITO CHOC 55G X6','Alfajor Jorgito Chocolate 55gr'],
  ['ALF JORGELIN LCHE 85','Alfajor Jorgelin Leche 85gr'],
  ['ALF.AGUILA BROWNIE 71.5','Alfajor Aguila Brownie 71,5gr'],
  ['CHOC.KINDER BUENO X2 43G','Chocolate Kinder Bueno  x2 43gr'],
  ['CHICLE BELDENT SANDIA 10G','Chicle Beldent Sandia 10gr'],
  ['GALL.OREO ORIG 118G','Galletita Oreo Original 118gr'],
  ['GALL.CHOCOLINAS 170G','Galletita Chocolinas 170gr'],
  ['GALL PITUSA FRUTILLA 160','Galletita Pitusa Frutilla 160gr'],
  ['LAVANDINA AYUDIN 1LT','Lavandina Ayudin Original 1L'],
  ['DET.ALA LIMON 300ML','Detergente Ala Concentrado Maximo Desengrase Limon 300ml'],
  ['JABON DOVE 90G','Jabon Dove Original 90gr'],
  ['SHAMP SEDAL CREMA BALANCE 190','Shampoo Sedal Crema Balance 190ml'],
  ['PILAS ENERGIZER AA','pilas energizer AA'],
  ['CIG.RED POINT BOX 20','Cigarrillo Red Point Box x20'],
  ['CIG PHILIP MORRIS X10','Cigarrillo Philip Morris x10'],
  ['CIG.LUCKY STRIKE XL BOX','Cigarrillo Lucky Strike XL Box x20'],
  ['CIG KIEL COMUN 20','Cigarrillo Kiel Comun x20'],
  ['TANG NARANJA DULCE 300G','Tang Naranja Dulce 300 g'],
  ['CAFE ARLISTAN 50G','Cafe Arlistan 50gr'],
  ['PEPSI BLACK LATA 354','Lata Pepsi Black 354ml'],
  // negativos
  ['CERV.ANDES ROJA 473',null],['GIN BOMBAY 750',null],['YERBA CANARIAS 1KG',null],['ALF.HAVANNA 70G',null],
  ['CIG.CAMEL BOX 20',null],['GALL.TRAVIATA 303G',null],['FERNET BRANCA MENTA 750',null],['COCA COLA 500CC',null],
];

// REV71: contraejemplos de la revisión de REV70 y variantes. Ninguno debe quedar elegido solo con el producto indicado en «no».
module.exports.revision=[
  // [texto impreso, descripción de la IA, producto que NO debe elegirse solo]
  ['ARROZ MOLINOS ALA 250G','Arroz Largo Fino Molinos Ala 1kg','Arroz Largo Fino Molinos Ala 1kg'],
  ['CERV.QUILMES LATA 473','Lata Cerveza Isenbeck 473ml','Lata Cerveza Isenbeck 473ml'],
  ['FERNET BRANCA 750CC','Vodka Skyy Raspberry 750ml','Fernet Branca 750ml'],
  ['CIG.MARLB.BOX X10','','Cigarrillo Marlboro Box x20'],
  ['CIG.MARLB.BOX X10','','Cigarrillo Marlboro Comun x20'],
  ['CHESTERFIELD COMUN X20','','Cigarrillo Chesterfield Comun x10'],
  ['LATA 473','Lata Cerveza Isenbeck 473ml','Lata Cerveza Isenbeck 473ml'],
  ['ACTRON 400','','actron 600'],
  // REV72: revisión de REV71 (con el catálogo real: los artículos equivalentes que existen en él).
  ['CIG MARLBORO BOX 10','','Cigarrillo Marlboro Box x20'],
  ['CIG MARLBORO COMUN 10','','Cigarrillo Marlboro Comun x20'],
  ['CHESTERFIELD COMUN 20','','Cigarrillo Chesterfield Comun x10'],
  ['ACTRON IBUPROFENO 400 MG','','Actrón Ibuprofeno 600 mg'],
  ['ACTRON IBUPROFENO 600 MCG','','Actrón Ibuprofeno 600 mg'],
  ['AGUA VILLAMANAOS 501 ML','','Agua Villamanaos 500 ml'],
  // REV73: revisión de REV72 (dosis con dos medidas y unidad solo en la factura), con artículos del catálogo real.
  ['ACTRON IBUPROFENO 400MG','','actron 600'],
  ['IBU 400MG','','ibu 600'],
  ['CHIZITOS KRACHITOS 480G','','chizitos krachitos'],
  // REV74: revisión de REV73 (el número del paquete no explica una medida), con artículos del catálogo real.
  // Con este catálogo REV73 tampoco los elegía solos (la reproducción de R73-01 es sintética); quedan como resguardo.
  ['ALFAJOR BON O BON 3GR X60','','Alfajor Bon o Bon x3 60gr'],
  ['HAMBURGUESA PATY EXPRESS 4GR X276','','Hamburguesa Paty Express x4 276gr'],
  ['CHOCOLATE KINDER BUENO 2GR X43','','Chocolate Kinder Bueno  x2 43gr'],
  // REV75: revisión de REV74 (la descripción de la IA omite un dato que el catálogo no confirma), con el catálogo real.
  ['Fideos Luchetti Codito 45 500gr','Fideos Luchetti Codito 500gr','Fideos Luchetti Codito 500gr'],
  ['Gomitas Sueltas 620gr','Gomitas Sueltas','Gomitas Sueltas'],
  ['Queso Dambo Punta del Agua 35gr','Queso Dambo Punta del Agua','Queso Dambo Punta del Agua'],
];
// REV77: factura real de MAYORISTA MI BARRIO (30/09/2026), con el producto que confirmó el dueño.
// No se usó para calibrar las reglas generales, pero sí motivó los cambios de REV77: se informa aparte.
module.exports.facturaReal=[
  ['MARLBORO COMUN','Cigarrillo Marlboro Comun x20'],
  ['LUCKY DE 20 NEGRO XL','Cigarrillo Lucky Strike XL Box x20'],
  ['PHILIP SELET','Cigarrillo Philip Morris Red Select Comun x20  trucho'],
  ['PHILLIP SELEC BLUE','Philip Morris Mentolado Blue Select x20 (trucho)'],
  ['CHESTER 10 NEGRO','Cigarrillo Chesterfield Convertible x10'],
  ['PHILLP DE 10 BCO','Cigarrillo Philip Morris x10'],
  ['MARLBORO FUSION2 DE 10','Cigarrillo Marlboro Purple Fusion x10'],
  ['MARLBORO FUSION2 DE 20','Cigarrillo Marlboro Purple Fusion Box  x20'],
  ['ALF MATILDA',null],
];
